[MOSIP-35421] Moved helm charts and installtion scripts of dslrig and…
mosip/mosip-automation-tests pull request #651
Opened 2024-09-12 08:16 UTC by Mohanraj209

… packetcreator.

2024-09-17 06:37 UTC, syedsalman3753 requested changes
Install script is missing

2024-09-17 10:47 UTC, Mohanraj209 commented
> Install script is missing

updated

2024-09-17 11:54 UTC, syedsalman3753 approved these changes

2024-09-19 05:20 UTC, ckm007 approved these changes

2024-09-19 05:20 UTC, merged