MOSIP-36029
mosip/mosip-automation-tests pull request #671
Opened 2024-10-28 08:29 UTC by pg-techno123

2024-10-30 05:18 UTC, lsivanand approved these changes

2024-11-05 13:36 UTC, mohanachandran-s requested changes

2024-11-05 13:36 UTC, mohanachandran-s commented on mosip-acceptance-tests/ivv-orchestrator/pom.xml
> +        <version>1.2.1-java21-SNAPSHOT</version>
In develop branch we should not use "java21" in version, it should be 1.2.1-SNAPSHOT

2024-11-05 13:36 UTC, mohanachandran-s commented on mosip-acceptance-tests/ivv-orchestrator/pom.xml
> +                <version>1.2.1-java21-SNAPSHOT</version>
Update the released version

2024-11-06 04:47 UTC, pg-techno123 commented on mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/CertificateController.java
> +	/*
Will remove post testing on rancher

2024-11-06 04:51 UTC, mohanachandran-s commented on mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/CertificateController.java
> +	/*
if it is for testing purpose, it is recommended to create image with profile docker and test it instead of merging into develop and testing

2024-11-06 08:45 UTC, mohanachandran-s commented on mosip-packet-creator/src/main/java/io/mosip/testrig/dslrig/packetcreator/controller/CertificateController.java
> +	/*
As confirmed by @pg-techno123,  After testing commented lines will be deleted

2024-11-07 09:47 UTC, merged